export interface TechStack {
  name: string;
  type: string;
  icon: string;
}

export interface Project {
  id: number;
  title: string;
  mainColor: string;
  type: string;
  yearCreated: string;
  projectGoal: string;
  logo: string;
  image: string;
  projectLink?: string;
  projectLinkGit?: string;
  overview: string;
  techStacks: TechStack[];
}

export const projects: Project[] = [
  {
    id: 0,
    title: 'Store Shoping',
    mainColor: '#00ADB5',
    type: 'Website',
    yearCreated: '2025',
    projectGoal: 'Presenting my work, skills and personal info.',
    logo: '',
    image: '',
    projectLink: '',
    projectLinkGit: 'https://github.com/Dark-Vol/Store-Shoping',
    overview: ``,
    techStacks: [
      {
        name: 'Sass',
        type: 'Stylesheets',
        icon: 'icon/Sass.svg',
      },
      {
        name: 'TypeScript',
        type: 'Programming Language',
        icon: 'icon/TypeScript.svg',
      },
      {
        name: 'React',
        type: 'Programming Language',
        icon: 'icon/React.svg',
      },
      {
        name: 'Nodejs',
        type: 'Programming Language',
        icon: 'icon/Node.js.svg',
      },
      {
        name: 'ExpressJS',
        type: 'Programming Language',
        icon: 'icon/Express.svg',
      },
      {
        name: 'MySql',
        type: 'Database',
        icon: 'icon/MySQL.svg',
      },
    ],
  },
  {
    id: 1,
    title: 'Organik',
    mainColor: '#FF6B35',
    type: 'Website',
    yearCreated: '2025',
    projectGoal: '',
    logo: '',
    image: '',
    projectLink: '',
    projectLinkGit: 'https://github.com/Dark-Vol/Organick',
    overview: ``,
    techStacks: [
      {
        name: 'Sass',
        type: 'Stylesheets',
        icon: 'icon/Sass.svg',
      },
      {
        name: 'TypeScript',
        type: 'Programming Language',
        icon: 'icon/TypeScript.svg',
      },
      {
        name: 'React',
        type: 'Programming Language',
        icon: 'icon/React.svg',
      },
      {
        name: 'React Router',
        type: 'Programming Language',
        icon: 'icon/React Bootstrap.svg',
      },
    ],
  },
  {
    id: 2,
    title: 'Ytyt',
    mainColor: '#4ECDC4',
    type: 'web-application',
    yearCreated: '2025',
    projectGoal: '',
    logo: '',
    image: 'projects/YtYt.png',
    projectLink: '',
    projectLinkGit: 'https://github.com/Dark-Vol/Ytyt',
    overview: `YtYt - это веб-приложение для онлайн-школы программирования, которая предлагает курсы по различным языкам программирования (Python, JavaScript, C#).
    Платформа включает систему управления студентами, группами, интерактивный редактор кода и современный пользовательский интерфейс.`,
    techStacks: [
      {
        name: 'CSS',
        type: 'Stylesheets',
        icon: 'icon/CSS3.svg',
      },
      {
        name: 'React',
        type: 'Programming Language',
        icon: 'icon/React.svg',
      },
      {
        name: 'TypeScript',
        type: 'Programming Language',
        icon: 'icon/TypeScript.svg',
      },
      {
        name: 'NextJs',
        type: 'Programming Language',
        icon: 'icon/Next.js.svg',
      },
    ],
  },
  {
    id: 3,
    title: 'poland24',
    mainColor: '#FFD93D',
    type: 'web-application',
    yearCreated: '2025',
    projectGoal: '',
    logo: '',
    image: '',
    projectLink: '',
    projectLinkGit: 'https://github.com/Dark-Vol/poland24',
    overview: `Платформа для заказов и доставки товаров из польских интернет-магазинов. Веб-приложение на Next.js с поддержкой мультиязычности и административной панелью.`,
    techStacks: [
      {
        name: 'CSS',
        type: 'Stylesheets',
        icon: 'icon/CSS3.svg',
      },
      {
        name: 'React',
        type: 'Programming Language',
        icon: 'icon/React.svg',
      },
      {
        name: 'TypeScript',
        type: 'Programming Language',
        icon: 'icon/TypeScript.svg',
      },
      {
        name: 'NextJs',
        type: 'Programming Language',
        icon: 'icon/Next.js.svg',
      },
      {
        name: 'Firebase',
        type: 'Programming Language',
        icon: 'icon/Firebase.svg',
      },
    ],
  },
  {
    id: 4,
    title: 'User Managmant Application',
    mainColor: '#6F00CA',
    type: 'application',
    yearCreated: '2025',
    projectGoal: '',
    logo: '',
    image: '',
    projectLink: '',
    projectLinkGit: 'https://github.com/Dark-Vol/nextjs-form-modal',
    overview: `Приложение для управления пользователями, построенное на Next.js 14 с использованием параллельных маршрутов (Parallel Routes) и перехватывающих маршрутов (Intercepting Routes) для реализации модальных окон.`,
    techStacks: [
      {
        name: 'TailwindCSS',
        type: 'Stylesheets',
        icon: 'icon/Tailwind CSS.svg',
      },
      {
        name: 'Sass',
        type: 'Stylesheets',
        icon: 'icon/Sass.svg',
      },
      {
        name: 'TypeScript',
        type: 'Programming Language',
        icon: 'icon/TypeScript.svg',
      },
      {
        name: 'React',
        type: 'Programming Language',
        icon: 'icon/React.svg',
      },
      {
        name: 'NextJs',
        type: 'Programming Language',
        icon: 'icon/Next.js.svg',
      },
      {
        name: 'Redux UI',
        type: 'Programming Language',
        icon: 'icon/Redux.svg',
      },
      {
        name: 'React Hook Form',
        type: 'Programming Language',
        icon: 'icon/React Bootstrap.svg',
      },
    ],
  },
  {
    id: 5,
    title: 'ToDo List Application',
    mainColor: '#A855F7',
    type: 'Mobile Application',
    yearCreated: '2025',
    projectGoal: '',
    logo: '',
    image: '',
    projectLink: '',
    projectLinkGit: 'https://github.com/Dark-Vol/ToDo-V.2.0-ReactNative',
    overview: `A modern to-do application built with React Native and Expo. Manage your tasks with a clean, intuitive interface that works on iOS, Android, and Web.`,
    techStacks: [
      {
        name: 'React Native',
        type: 'Programming Language',
        icon: '',
      },
      {
        name: 'TypeScript',
        type: 'Programming Language',
        icon: 'icon/TypeScript.svg',
      },
      {
        name: 'Expo',
        type: 'Programming Language',
        icon: '',
      },
      {
        name: 'Expo Router',
        type: 'Programming Language',
        icon: '',
      },
      {
        name: 'React Hook',
        type: 'Programming Language',
        icon: 'icon/React Bootstrap.svg',
      },
    ],
  },
  {
    id: 6,
    title: 'Web Librery',
    mainColor: '#DC143C',
    type: 'Web application',
    yearCreated: '2026',
    projectGoal: '',
    logo: '',
    image: '',
    projectLink: '',
    projectLinkGit: 'https://github.com/Dark-Vol/My-Librery',
    overview: `Полнофункциональное веб-приложение для управления библиотекой книг с современным Angular фронтендом и Node.js/Express бэкендом.`,
    techStacks: [
      {
        name: 'Sass',
        type: 'Stylesheets',
        icon: 'icon/Sass.svg',
      },
      {
        name: 'Angular',
        type: 'Programming Language',
        icon: 'icon/Angular.svg',
      },
      {
        name: 'TypeScript',
        type: 'Programming Language',
        icon: 'icon/TypeScript.svg',
      },
      {
        name: 'Nodejs',
        type: 'Programming Language',
        icon: 'icon/Node.js.svg',
      },
      {
        name: 'ExpressJS',
        type: 'Programming Language',
        icon: 'icon/Express.svg',
      },
    ],
  },
  {
    id: 7,
    title: 'React Web application',
    mainColor: '#FF6347',
    type: 'web application fpr weather',
    yearCreated: '2025',
    projectGoal: '',
    logo: '',
    image: '',
    projectLink: '',
    projectLinkGit: 'https://github.com/Dark-Vol/react_users_weather',
    overview: ``,
    techStacks: [
      {
        name: 'Sass',
        type: 'Stylesheets',
        icon: 'icon/Sass.svg',
      },
      {
        name: 'React',
        type: 'Programming Language',
        icon: 'icon/React.svg',
      },
      {
        name: 'TypeScript',
        type: 'Programming Language',
        icon: 'icon/TypeScript.svg',
      },
      {
        name: 'NextJs',
        type: 'Programming Language',
        icon: 'icon/Next.js.svg',
      },
      {
        name: 'Axios',
        type: 'Programming Language',
        icon: '',
      },
    ],
  },
  {
    id: 8,
    title: 'Angular Web application',
    mainColor: '#20B2AA',
    type: 'web application fpr weather',
    yearCreated: '2025',
    projectGoal: '',
    logo: '',
    image: '',
    projectLink: '',
    projectLinkGit: 'https://github.com/Dark-Vol/angular_users_weather',
    overview: ``,
    techStacks: [
      {
        name: 'Sass',
        type: 'Stylesheets',
        icon: 'icon/Sass.svg',
      },
      {
        name: 'Angular',
        type: 'Programming Language',
        icon: 'icon/Angular.svg',
      },
      {
        name: 'TypeScript',
        type: 'Programming Language',
        icon: 'icon/TypeScript.svg',
      },
      {
        name: 'Axios',
        type: 'Programming Language',
        icon: '',
      },
    ],
  },
  {
    id: 9,
    title: 'Bot application',
    mainColor: '#FF4500',
    type: 'Telegram Bot',
    yearCreated: '2025',
    projectGoal: '',
    logo: '',
    image: '',
    projectLink: '',
    projectLinkGit: 'https://github.com/Dark-Vol/vertikal_akva_bot',
    overview: `Телеграм-бот для предоставления информации об услугах, тренерах и программах фитнес-комплекса Вертикаль Аква.`,
    techStacks: [
      {
        name: 'Python',
        type: 'Programming Language',
        icon: 'icon/Python.svg',
      },
      {
        name: 'Telethon',
        type: 'Programming Language',
        icon: '',
      },
      {
        name: 'SQLite3',
        type: 'Programming Language',
        icon: 'icon/SQLite.svg',
      },
      {
        name: 'Python Telegram Bot',
        type: 'Programming Language',
        icon: '',
      },
    ],
  },
  {
    id: 10,
    title: 'Online School',
    mainColor: '#9370DB',
    type: 'web application',
    yearCreated: '2025',
    projectGoal: '',
    logo: '',
    image: '',
    projectLink: '',
    projectLinkGit: 'https://github.com/Dark-Vol/createx',
    overview: `A modern online learning platform built with React and TypeScript. Createx Online School provides a comprehensive educational experience with courses, events, blog posts, and user authentication.`,
    techStacks: [
      {
        name: 'Sass',
        type: 'Stylesheets',
        icon: 'icon/Sass.svg',
      },
      {
        name: 'TilwindCSS',
        type: 'Stylesheets',
        icon: 'icon/Tailwind CSS.svg',
      },
      {
        name: 'React',
        type: 'Programming Language',
        icon: 'icon/React.svg',
      },
      {
        name: 'TypeScript',
        type: 'Programming Language',
        icon: 'icon/TypeScript.svg',
      },
      {
        name: 'React Router',
        type: 'Programming Language',
        icon: 'icon/React Bootstrap.svg',
      },
      {
        name: 'Vite',
        type: 'Programming Language',
        icon: '',
      },
      {
        name: 'Firebase',
        type: 'Programming Language',
        icon: 'icon/Firebase.svg',
      },
      {
        name: 'React Hook Form',
        type: 'Programming Language',
        icon: 'icon/React Bootstrap.svg',
      },
    ],
  },
  {
    id: 11,
    title: 'Ics Analysic Tool',
    mainColor: '#00CED1',
    type: 'Tool for analysing ics systems',
    yearCreated: '2025',
    projectGoal: '',
    logo: '',
    image: '',
    projectLink: '',
    projectLinkGit: '',
    overview: ``,
    techStacks: [
      {
        name: 'Python',
        type: 'Programming Language',
        icon: 'icon/Python.svg',
      },
      {
        name: 'Pandas',
        type: 'Programming Language',
        icon: 'icon/Pandas.svg',
      },
      {
        name: 'NumPy',
        type: 'Programming Language',
        icon: 'icon/NumPy.svg',
      },
      {
        name: 'Matplotlib',
        type: 'Programming Language',
        icon: 'icon/Matplotlib.svg',
      },
      {
        name: 'Seaborn',
        type: 'Programming Language',
        icon: 'icon/Seaborn.svg',
      },
      {
        name: 'GUI Tkinter',
        type: 'Programming Language',
        icon: 'icon/Tkinter.svg',
      },
    ],
  },
  {
    id: 12,
    title: 'Interface Application',
    mainColor: '#FF1493',
    type: '',
    yearCreated: '',
    projectGoal: '',
    logo: '',
    image: '',
    projectLink: '',
    projectLinkGit: '',
    overview: ``,
    techStacks: [
      {
        name: 'CSS',
        type: 'Stylesheets',
        icon: 'icon/CSS3.svg',
      },
      {
        name: 'TailwindCSS',
        type: 'Stylesheets',
        icon: 'icon/Tailwind CSS.svg',
      },
      {
        name: 'React',
        type: 'Programming Language',
        icon: 'icon/React.svg',
      },
      {
        name: 'TypeScript',
        type: 'Programming Language',
        icon: 'icon/TypeScript.svg',
      },
      {
        name: 'NextJs',
        type: 'Programming Language',
        icon: 'icon/Next.js.svg',
      },
      {
        name: 'React Router',
        type: 'Programming Language',
        icon: 'icon/React Bootstrap.svg',
      },
    ],
  },
  {
    id: 13,
    title: 'Chess Wars',
    mainColor: '#32CD32',
    type: 'Python Game',
    yearCreated: '',
    projectGoal: '',
    logo: '',
    image: '',
    projectLink: '',
    projectLinkGit: '',
    overview: ``,
    techStacks: [
      {
        name: 'Python',
        type: 'Programming Language',
        icon: 'icon/Python.svg',
      },
      {
        name: 'Pygame',
        type: 'Programming Language',
        icon: '',
      },
      {
        name: 'Pandas',
        type: 'Programming Language',
        icon: 'icon/Pandas.svg',
      },
      {
        name: 'NumPy',
        type: 'Programming Language',
        icon: 'icon/NumPy.svg',
      },
    ],
  },
  {
    id: 14,
    title: 'Pytest',
    mainColor: '#FF8C00',
    type: 'Testing Framework',
    yearCreated: '',
    projectGoal: '',
    logo: '',
    image: '',
    projectLink: '',
    projectLinkGit: '',
    overview: ``,
    techStacks: [
      {
        name: 'pytest',
        type: 'Programming Language',
        icon: 'icon/pytest.svg',
      },
      {
        name: 'Python',
        type: 'Programming Language',
        icon: 'icon/Python.svg',
      },
      {
        name: 'Math',
        type: 'Programming Language',
        icon: 'icon/Matplotlib.svg',
      },
      {
        name: 'functions',
        type: 'Programming Language',
        icon: '',
      },
    ],
  },
  {
    id: 15,
    title: 'dydxGrants',
    mainColor: '#1E90FF',
    type: 'web application',
    yearCreated: '',
    projectGoal: '',
    logo: '',
    image: '',
    projectLink: '',
    projectLinkGit: '',
    overview: ``,
    techStacks: [
      {
        name: 'CSS',
        type: 'Stylesheets',
        icon: 'icon/CSS3.svg',
      },
      {
        name: 'HTML',
        type: 'Programming Language',
        icon: 'icon/HTML5.svg',
      },
      {
        name: 'Javascript',
        type: 'Programming Language',
        icon: 'icon/JavaScript.svg',
      },
    ],
  },
  {
    id: 16,
    title: 'Coffee-Mugs',
    mainColor: '#FF69B4',
    type: 'web application',
    yearCreated: '',
    projectGoal: '',
    logo: '',
    image: '',
    projectLink: '',
    projectLinkGit: '',
    overview: ``,
    techStacks: [
      {
        name: 'CSS',
        type: 'Stylesheets',
        icon: 'icon/CSS3.svg',
      },
      {
        name: 'HTML',
        type: 'Programming Language',
        icon: 'icon/HTML5.svg',
      },
      {
        name: 'Javascript',
        type: 'Programming Language',
        icon: 'icon/JavaScript.svg',
      },
      {
        name: '',
        type: 'Programming Language',
        icon: '',
      },
      {
        name: 'Fonts',
        type: 'Programming Language',
        icon: '',
      },
    ],
  },
  {
    id: 17,
    title: 'Createx-Marathon',
    mainColor: '#00FF7F',
    type: 'web application',
    yearCreated: '',
    projectGoal: '',
    logo: '',
    image: '',
    projectLink: '',
    projectLinkGit: '',
    overview: ``,
    techStacks: [
      {
        name: 'SaSS',
        type: 'Stylesheets',
        icon: 'icon/Sass.svg',
      },
      {
        name: 'CSS',
        type: 'Stylesheets',
        icon: 'icon/CSS3.svg',
      },
      {
        name: 'Html',
        type: 'Programming Language',
        icon: 'icon/HTML5.svg',
      },
      {
        name: 'Javascript',
        type: 'Programming Language',
        icon: 'icon/JavaScript.svg',
      },
    ],
  },
  {
    id: 18,
    title: 'CLI Python',
    mainColor: '#FFB6C1',
    type: 'CLI App Python: Typer + Rich',
    yearCreated: '2025',
    projectGoal: '',
    logo: '',
    image: '',
    projectLink: '',
    projectLinkGit: '',
    overview: ``,
    techStacks: [
      {
        name: 'typer ',
        type: 'Programming Language',
        icon: '',
      },
      {
        name: 'Python',
        type: 'Programming Language',
        icon: 'icon/Python.svg',
      },
    ],
  },
  {
    id: 19,
    title: 'GUI Scripts for markdown',
    mainColor: '#7B68EE',
    type: 'Markdown GUI Application',
    yearCreated: '2025',
    projectGoal: '',
    logo: '',
    image: '',
    projectLink: '',
    projectLinkGit: '',
    overview: ``,
    techStacks: [
      {
        name: 'Flet',
        type: 'Programming Language',
        icon: '',
      },
      {
        name: 'Python',
        type: 'Programming Language',
        icon: 'icon/Python.svg',
      },
    ],
  },
  {
    id: 20,
    title: 'plubexer',
    mainColor: '#48D1CC',
    type: 'Web application',
    yearCreated: '2025',
    projectGoal: '',
    logo: '',
    image: '',
    projectLink: '',
    projectLinkGit: '',
    overview: ``,
    techStacks: [
      {
        name: 'Sass',
        type: 'Stylesheets',
        icon: 'icon/Sass.svg',
      },
      {
        name: 'React',
        type: 'Programming Language',
        icon: 'icon/React.svg',
      },
      {
        name: 'TypeScript',
        type: 'Programming Language',
        icon: 'icon/TypeScript.svg',
      },
      {
        name: 'NextJs',
        type: 'Programming Language',
        icon: 'icon/Next.js.svg',
      },
      {
        name: 'React Router',
        type: 'Programming Language',
        icon: 'icon/React Bootstrap.svg',
      },
    ],
  },
  {
    id: 21,
    title: 'Warhammer bot',
    mainColor: '#DA70D6',
    type: 'Telegram Bot',
    yearCreated: '2025',
    projectGoal: '',
    logo: '',
    image: '',
    projectLink: '',
    projectLinkGit: '',
    overview: ``,
    techStacks: [
      {
        name: 'Telegram',
        type: 'Programming Language',
        icon: '',
      },
      {
        name: 'Python',
        type: 'Programming Language',
        icon: 'icon/Python.svg',
      },
      {
        name: 'Telegram.ext',
        type: 'Programming Language',
        icon: '',
      },
      {
        name: 'OS',
        type: 'Programming Language',
        icon: '',
      },
      {
        name: 'JSON',
        type: 'Programming Language',
        icon: 'icon/JSON.svg',
      },
      {
        name: 'Datatime',
        type: 'Programming Language',
        icon: '',
      },
    ],
  },
  {
    id: 22,
    title: 'Todo list React Native',
    mainColor: '#FFA500',
    type: 'Mobile Application',
    yearCreated: '2025',
    projectGoal: '',
    logo: '',
    image: '',
    projectLink: '',
    projectLinkGit: '',
    overview: ``,
    techStacks: [
      {
        name: 'React Native',
        type: 'Programming Language',
        icon: '',
      },
      {
        name: 'React',
        type: 'Programming Language',
        icon: 'icon/React.svg',
      },
      {
        name: 'Expo',
        type: 'Programming Language',
        icon: '',
      },
      {
        name: 'Expo Status Bar',
        type: 'Programming Language',
        icon: '',
      },
    ],
  },
  {
    id: 23,
    title: 'WorkTap',
    mainColor: '#40E0D0',
    type: 'Web Application',
    yearCreated: '2025',
    projectGoal: '',
    logo: '',
    image: '',
    projectLink: '',
    projectLinkGit: '',
    overview: ``,
    techStacks: [
      {
        name: 'CSS',
        type: 'Stylesheets',
        icon: 'icon/CSS3.svg',
      },
      {
        name: 'TailwindCSS',
        type: 'Stylesheets',
        icon: 'icon/Tailwind CSS.svg',
      },
      {
        name: 'TypeScript',
        type: 'Programming Language',
        icon: 'icon/TypeScript.svg',
      },
      {
        name: 'NextJs',
        type: 'Programming Language',
        icon: 'icon/Next.js.svg',
      },
      {
        name: 'React',
        type: 'Programming Language',
        icon: 'icon/React.svg',
      },
      {
        name: 'React Router',
        type: 'Programming Language',
        icon: 'icon/React Bootstrap.svg',
      },
    ],
  },
  {
    id: 24,
    title: 'News App',
    mainColor: '#9B59B6',
    type: 'React Native Application',
    yearCreated: '2025',
    projectGoal: '',
    logo: '',
    image: '',
    projectLink: '',
    projectLinkGit: '',
    overview: ``,
    techStacks: [
      {
        name: 'React Native',
        type: 'Programming Language',
        icon: 'icon/icons8-react-native-100.svg',
      },
      {
        name: 'Expo',
        type: 'Programming Language',
        icon: '',
      },
      {
        name: 'Javascript',
        type: 'Programming Language',
        icon: 'icon/JavaScript.svg',
      },
      {
        name: 'Expo Status Bar',
        type: 'Programming Language',
        icon: '',
      },
    ],
  },
  {
    id: 25,
    title: 'Event Tracker App',
    mainColor: '#9B59B6',
    type: 'Web Application',
    yearCreated: '2026',
    projectGoal: '',
    logo: '',
    image: '',
    projectLink: '',
    projectLinkGit: '',
    overview: ``,
    techStacks: [
      {
        name: 'Angular',
        type: 'Programming Language',
        icon: 'icon/Angular.svg',
      },
      {
        name: 'TypeScript',
        type: 'Programming Language',
        icon: 'icon/TypeScript.svg',
      },
      {
        name: 'SASS',
        type: 'Programming Language',
        icon: 'icon/Sass.svg',
      },
      {
        name: 'HTML',
        type: 'Programming Language',
        icon: 'icon/HTML5.svg',
      },
    ],
  },
  {
    id: 26,
    title: 'NoteCore++',
    mainColor: '#00599C',
    type: 'C++ Application',
    yearCreated: '2026',
    projectGoal: '',
    logo: '',
    image: '',
    projectLink: '',
    projectLinkGit: 'https://github.com/Dark-Vol/NoteCore-',
    overview: `NoteCore++ — это демонстрационный проект, показывающий зрелый подход к архитектуре на C++. Проект демонстрирует:
    Layered Architecture — разделение на слои (Domain, Application, Infrastructure, Presentation)
    SOLID принципы — особенно Dependency Inversion
    Чистую архитектуру — бизнес-логика независима от деталей реализации
    Расширяемость — легко перейти от CLI к GUI, от файлов к БД`,
    techStacks: [
      {
        name: 'C++',
        type: 'Programming Language',
        icon: 'icon/C++ (CPlusPlus).svg',
      },
      {
        name: 'CMake',
        type: 'Programming Language',
        icon: 'icon/CMake.svg',
      },
      {
        name: 'Catch2',
        type: 'Programming Language',
        icon: '',
      },
      {
        name: "PowerShell",
        type: 'Programming Language',
        icon: 'icon/Powershell.svg',
      },
      {
        name: "Batchifile",
        type: 'Programming Language',
        icon: '',
      }
    ],
  },
  //   {
  //   id: 26,
  //   title: 'News App',
  //   mainColor: '#9B59B6',
  //   type: 'React Native Application',
  //   yearCreated: '2025',
  //   projectGoal: '',
  //   logo: '',
  //   image: '',
  //   projectLink: '',
  //   projectLinkGit: '',
  //   overview: ``,
  //   techStacks: [
  //     {
  //       name: 'React Native',
  //       type: 'Programming Language',
  //       icon: 'icon/icons8-react-native-100.svg',
  //     },
  //     {
  //       name: 'Expo',
  //       type: 'Programming Language',
  //       icon: '',
  //     },
  //     {
  //       name: 'Javascript',
  //       type: 'Programming Language',
  //       icon: 'icon/JavaScript.svg',
  //     },
  //     {
  //       name: 'Expo Status Bar',
  //       type: 'Programming Language',
  //       icon: '',
  //     },

  //   ],
  // },
];
